import Head from 'next/head';
import * as UI from '@mantine/core';
import { Search } from 'react-feather';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Home Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<UI.Center>
				<UI.Title order={1}>
					This is my project!
				</UI.Title>

				<UI.Button color="violet" radius="md" size="md">
					<UI.Text>Search</UI.Text>
					<Search size="18" />
				</UI.Button>
			</UI.Center>
		</div>
	)
}
